#!/bin/sh

case $1 in
	start)
		sudo systemctl start trek-srv
		;;
	stop)
		sudo systemctl stop trek-srv
		sleep 20 
		;;
	restart)
		sudo systemctl stop trek-srv
		sleep 20
		sudo systemctl start trek-srv
		;;
	status)
		sudo systemctl status trek-srv
		;;
	update)
		sudo systemctl stop trek-srv
		git pull
		sleep 20
		sudo systemctl start trek-srv
		;;
	*)
		echo "Usage: trek start|stop|restart|status"
esac
