map:

  scale: 1
  
  realistic-physics:
    object-pathing:
      system-members: true
      systems: true
    tick-events:
      enable-rogue-objects: true
      enable-stellar-lifecycle: true
      gravity-affects-players: true
    
  gameplay:
    spawn-hostile-ai: true
  
