universe:
    spawn-rogue-objects: true
    realistic-physics: true
    radius:
        min: 2.3
        max: 4.6
    unit: 10e9 ly
    
galaxy:
    unit: ??
    spawn-density:
        min: 1
        max: 50
    spawn-potentials:
        spiral:
            weight: 0.75
            radius:
                min: 16
                max: 350
            rotation: sqrt(GM/r)
            sys-spawn-distr: random
        elliptical:
            weight: 0.2
            radius:
                min: 3
                max: 700
            rotation: false
            sys-spawn-distr: random
        irregular:
            weight: 0.05
            radius:
                min: 18
                max: 25
            rotation: false
            sys-spawn-distr: cluster
            
system:
    radius:
        min: ??
        max: ??
    bodies:
        min: 1
        max: 10
    unit: 
    central-body-spawn-potentials:
        star:
            weight: 0.8
        remnant:
            weight: 0.2
    orbiting-body-spawn-potentials:
        
            
star:
    mass:
        min: 0.5
        max: 100
    radius:
        min: ??
        max: ??
    spawn-potentials:
        main-sequence:
            weight: 0.9
        giant:
            weight: 0.1
            
remnant:
    spawn-potentials:
        white-dwarf:
            weight: 0.5
            mass:
                min: 0.15
                max: 1.4
        neutron-star:
            weight: 0.25
            mass:
                min: 1.1
                max: 2.1
        black-hole:
            weight: 0.25
            mass:
                min: 5
                max: 35
                
planetoid:
    orbital-period: 2*pi*sqrt(a^3/GM)
    spawn-potentials:
        terrestrial:
            mass:
                min: 0.1 M_earth
                max: 10 M_earth
            distance:
                min: 0.1 AU
                max: 2 AU
            rotation-period:
                min: 20h
                max: 60d
        gas-giant:
            mass:
                min: 75 M_earth
                max: 13 M_jupiter
            distance:
                min: 5 AU
                max: 30 AU
            rotation-period:
                min: 8h
                max: 20h
        ice-giant:
            mass:
                min: 10 M_earth
                max: 25 M_earth
            distance:
                min: 5 AU
                max: 30 AU
            rotation-period:
                min: 8h
                max: 20h
        
           
