
unit: ??
spawn-potentials:
    spiral: 0.75
    elliptical: 0.2
    irregular: 0.05
system-density:
    min: 1
    max: 50
    
    
    
    
    
#   spiral:
#        radius:
#            min: 16
#            max: 350
#        rotation: sqrt(GM/r)
#        sys-spawn-distr: random    
#    elliptical:
#        radius:
#            min: 3
#            max: 700
#        rotation: false
#        sys-spawn-distr: random
#    irregular:
#        radius:
#            min: 18
#            max: 25
#        rotation: false
#        sys-spawn-distr: cluster
            
