galaxy:
    unit: ??
    spawn-density:
        min: 1
        max: 50
    spawn-potentials:
        spiral:
            weight: 0.75
            radius:
                min: 16
                max: 350
            rotation: sqrt(GM/r)
            sys-spawn-distr: random
        elliptical:
            weight: 0.2
            radius:
                min: 3
                max: 700
            rotation: false
            sys-spawn-distr: random
        irregular:
            weight: 0.05
            radius:
                min: 18
                max: 25
            rotation: false
            sys-spawn-distr: cluster
            
